# Generated by Django 3.1.1 on 2020-11-09 17:10

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('autos_dj4e', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='make',
            name='name',
            field=models.CharField(help_text='(eg.Honda)', max_length=200, validators=[django.core.validators.MinLengthValidator(5, 'minimum 5 characters required.')]),
        ),
    ]
