# Generated by Django 3.1.1 on 2020-11-10 09:48

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('autos_dj4e', '0003_auto_20201110_1300'),
    ]

    operations = [
        migrations.AlterField(
            model_name='make',
            name='name',
            field=models.CharField(help_text='(eg.Honda)', max_length=200, validators=[django.core.validators.MinLengthValidator(2, 'minimum 2 characters required.')], verbose_name='Name(Auto):'),
        ),
    ]
