# Generated by Django 3.1.1 on 2020-11-01 03:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('MusicLib', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='album',
            old_name='Artist_id',
            new_name='Artist',
        ),
        migrations.RenameField(
            model_name='track',
            old_name='album_id',
            new_name='album',
        ),
    ]
